### PR TITLE
Supporting Ethiopian Calendar Widget #1113

### PR DESCRIPTION
**Pull request by aurdipas**
tested in Ethiopia from Ethiopian Public Health Association (EPHA)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks, @aurdipas!! Awesome to see that it's even been tested in Ethiopia!

We're working on a patch release 1.9.1 now with only bug fixes and then we'll start reviewing and merging features like this one. 

One thing I'm wondering about is whether adding an "ethiopian" appearance is the best approach. That's what CommCare does so it's certainly not bad. We're trying to be consistent about using appearances for optional client hints that can safely be ignored. Is it ok if the calendar falls back to the Gregorian calendar in this case if an ODK client that doesn't know the "ethiopian" appearance is used?

**Comment by lognaturel** [comment]
Hi @aurdipas! There are a couple of compilation errors! It looks like there are also some [checkstyle](https://751-40213809-gh.circle-artifacts.com/0/tmp/circle-junit.10FiUUc/checkstyle/checkstyle.html) and lint errors (the array of months in Amharic is duplicated).

Once I fixed those locally, I was able to run it and it looks like it works well with the form [ethiopian-cal.txt](https://github.com/opendatakit/collect/files/1219254/ethiopian-cal.txt)! 🎉

I think before merging we should try to match the interface of the current calendar widget as closely as possible.

**Comment by lognaturel** [comment]
Thank you, @aurdipas! @grzesiek2010 has started work off your branch and you can see his progress at #1470. I'll close this one in favor of that one. Please leave your branch around so that we can refer back to it if needed!
