### PR TITLE
Revert left-to-right characters

### PR DESCRIPTION
**Pull request by lognaturel**
These were introduced in #2123 probably to ensure a certain order of the text in parentheses even when using RTL languages.

I noticed when updating translations for the release that translations of those strings had been lost because the base English string had changed. I don't think introducing those ltr characters there is a great option because it is confusing to translators.

PR #2123 also introduced LTR characters where certain values were appended together (e.g. `.append(")\u200E");`). This does make sense because otherwise appending would go to the left in a RTL language. Another option would have been to use a format string.

I looked at the app in Arabic before the change and on the main screen, the numbers in parentheses appeared where and how I would expect them. I don't think those LTR characters are needed. It also appears the string `Sending %1$s of %2$s form(s)\u200E` doesn't follow the same pattern as the others so it's even less clear why that one was added.

@huangyz0918 Can you please share a bit more about why those characters were added to the strings and what effect you expect them to have? I apologize for not bringing this up in review -- for some reason I didn't really think through it then!

I propose we merge this change now and revert the translations so that we don't have missing translations. If it turns out a change like this was needed we can see how best to approach it.

#### What has been done to verify that this works as intended?
This is not a functional change. Ran the app to make sure it still compiled and ran.

#### Why is this the best possible solution? Were any other approaches considered?
The short term goal is to bring back the translations that were lost by this change (when a string in the base language changes, translations are lost for that string). 

#### Are there any risks to merging this code? If so, what are they?
None that I can think of. We will need to manually revert the translations in Transifex.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by yanokwa — COMMENTED** [review]
This explanation is clear to me and this reversion is the smallest change that gets us back on track for the release.

It sounds like this change snuck in after testing, so as a process change, we have to be more diligent about steping through commits after testing to make sure those fixes are targeted. 

@huangyz0918 If you are making a change that doesn't target the issue found in testing, a comment in the PR would help reviewers catch these mistakes.

Mistakes will happen, we just have to learn from them! In the grand scheme of things, this is pretty minor.

**Review by yanokwa — APPROVED** [review]

**Comment by huangyz0918** [comment]
An interesting thing is: when we are under RTL languages, the brackets (at the end of the text) is incorrect in Android 4.4 and 4.2. The code `\u200e` is added to fix this. I didn’t think much about this, but if we actually need the changes I can do a deeper testing and fix this via java code.

**Comment by lognaturel** [comment]
Sorry I missed this, @huangyz0918! 

I completely agree with your fix for the breadcrumbs and that one works well.

Did you actually see the problem on the main screen (where `Edit Saved Form (%s)‎‎‎‎` shows up)? And what about with an actual RTL language? I think this may be addressed by the translations themselves. For example, if you look at the `review_data_button` in Arabic in Android Studio, you'll see that the `(%s)` part is LTR.

**Comment by huangyz0918** [comment]
>Did you actually see the problem on the main screen (where Edit Saved Form (%s)‎‎‎‎ shows up)?

Yes, this is why I made changes in `string.xml`. I also noticed that in sending forms dialog.

> And what about with an actual RTL language? 

brackets work well in LTR, this issue only happens in actual RTL.  

> I think this may be addressed by the translations themselves. 

You are right. But I'm curious why this only happened in specific android apis.

**Comment by lognaturel** [comment]
> this issue only happens in actual RTL.

What's a language you can see the problem in?

> I'm curious why this only happened in specific android apis.

Ahh, the mysteries of Android. Support for RTL languages before API 17 was poor across the board (as you've seen) so I'm not really surprised.
